# .github/workflows/sast-scan.yml
name: Remote SAST Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger OCI SAST API
        run: |
          # -H 옵션을 사용하여 헤더에 API Key를 포함합니다.
          # ${{ secrets.SAST_API_KEY }}는 깃허브가 자동으로 마스킹하여 안전하게 전달합니다.
          curl -X GET "http://168.107.27.132:8000/scan-git?repo_url=https://github.com/${{ github.repository }}" \
               -H "x-api-key: ${{ secrets.SAST_API_KEY }}"
